# site settings

title: Jude
description: Jude theme for a beautiful online CV
taglong: Juse theme for a beautiful online CV
tagshort: Jude theme
url: https://jude-san.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/jude-san/jude-san.github.io

# author settings

author:
  name: jude Koomson
  email: judekhay@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  facebook: Judenyamekye
  github: jude-san
  instagram: username
  linkedin: wwww.linkedin.com/in/judenyamekye
  stackoverflow: 0000000/username
  twitter: judesan

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
